HOSTS:
  centos-6-x64:
    platform: el-6-x86_64
    image: centos:centos6
    hypervisor: docker
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
    - 'yum install -y wget tar ntpdate rubygems ruby-augeas ruby-devel augeas-devel'
    - 'touch /etc/sysconfig/network'
    docker_preserve_image: true
CONFIG:
  log_level: debug
  type: aio
